### ISSUE TITLE
[Docs] Creating conda environment from root YAML does not work for macOS

### ISSUE THREAD

**Issue by larsmaxfield** [olive-groves/butterfly_viewer#19]
If I create a conda environment in macOS using `environment.yml`, I get a "Packages not found" error.

I was able to get an environment working with:
```
conda config --append channels conda-forge
conda create --prefix ./env python=3.7
conda activate ./env
conda install pyqt=5.9
conda install piexif
```

I propose editing the Developers documentation to include steps to "manually" install the environment as I've done.

**Comment by NagabhushanSN95** [comment]
@larsmaxfield can you please list out the steps atleast here so that I can follow that until the documentation is updated

**Comment by larsmaxfield** [comment]
@NagabhushanSN95 I won't be able to verify this for a couple weeks as I don't have access to a Mac, but the main steps (if I recall correctly) should be these:

- Install Anaconda, ensuring Anaconda Prompt is accessible afterwards

- Clone the repo (or otherwise download the repo) to a local folder you can locate

- Open Anaconda Prompt

- In Anaconda Prompt, do this:
  - Change directory to the repo's root (where you something like `cd Users/YourUsername/Documents/butterfly_viewer`)
  - Run the conda commands I posted above in order:
```
conda config --append channels conda-forge
conda create --prefix ./env python=3.7
conda activate ./env
conda install pyqt=5.9
conda install piexif
```
  - Change directory to the source subfolder with `cd butterfly_viewer`
  - Run the Viewer with `python butterfly_viewer.py`

**Comment by larsmaxfield** [comment]
@NagabhushanSN95 I won't be able to verify this for a couple weeks as I don't have access to a Mac, but the main steps (if I recall correctly) should be these:

- Install Anaconda, ensuring Anaconda Prompt is accessible afterwards

- Clone the repo (or otherwise download the repo) to a local folder you can locate

- Open Anaconda Prompt

- In Anaconda Prompt, do this:
  - Change directory to the repo's root (where you something like `cd Users/YourUsername/Documents/butterfly_viewer`)
  - Run the conda commands I posted above in order:
```
conda config --append channels conda-forge
conda create --prefix ./env python=3.7
conda activate ./env
conda install pyqt=5.9
conda install piexif
```
  - Change directory to the source subfolder with `cd butterfly_viewer`
  - Run the Viewer with `python butterfly_viewer.py`
