### ISSUE TITLE
[Feature] <I want to compare multiple image versions after upscaling>

### ISSUE THREAD

**Issue by alethinh** [olive-groves/butterfly_viewer#32]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I want to compare multiple image versions after upscaling

**Comment by larsmaxfield** [comment]
Hi @alethinh, it's not clear to me what this feature would look like. Can you provide more details? An illustration of what you envision or a sequence of user actions would be useful.

**Comment by alethinh** [comment]
Butterfly Viewer
https://live.staticflickr.com/65535/53505319801_7ad7b7caa1_k.jpg

Butterfly Viewer does not show synchronous dimensions

FastStone Image Viewer (4 images compare)
https://live.staticflickr.com/65535/53505312606_0509c5e8d5_k.jpg

With Butterfly Viewer's drag and drop feature, I can place images in different locations on the hard drive
As for FastStone Viewer, those images must be in the same folder location

**Comment by larsmaxfield** [comment]
Thanks @alethinh. Makes sense.

Indeed the Butterfly Viewer synchronizes the pixel size, not the dimensions.

I'm not sure how easy it will be to implement this in the backend, but on the interface I think a simple "sync by dimensions" toggle would suffice in the right-click menu.

I will take a look.

**Comment by larsmaxfield** [comment]
@alethinh I believe I've found a solution which will be straightforward to implement. However, I likely won't be able to fully implement it until later next month (March). I'll keep you updated.

**Comment by alethinh** [comment]
That's great, wish you success with your work, relax with life

**Comment by larsmaxfield** [comment]
@alethinh I've implemented the solution and pushed it to `main`!

I will generate the Windows and MacOS versions for the official release (#31) once I've updated the docs (#41).

Sliding overlays still require that images have the same dimensions for them to be compared 1:1 in a given sliding overlay window. It does not relatively scale them... yet (#42).

**Comment by larsmaxfield** [comment]
Automatic image scaling is now available for Windows and macOS [in the latest release](https://github.com/olive-groves/butterfly_viewer/releases/latest).

**Comment by alethinh** [comment]
> Automatic image scaling is now available for Windows and macOS [in the latest release](https://github.com/olive-groves/butterfly_viewer/releases/latest).

Hello, it's been a while since I replied to your message. You've tried your best to work. I admire you for your community
