### ISSUE TITLE
[Feature] Start from command line, taking the paths of the images to compare as paramters

### ISSUE THREAD

**Issue by icue** [olive-groves/butterfly_viewer#44]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I'm using Windows, and my current workflow with butterfly viewer is often: locate the two images in explorer (which are often in two different folders), open butterfly viewer, switch to explorer again, drag them into butterfly viewer, and click on the "create" button in the sliding overlay creator.
This is not the most efficient way to start the comparison. All these preparation work is bringing overhead and friction, especially when I have lots of pairs of images to compare.

### Describe the solution you'd like

In cmd, simply with "butterfly_viewer.exe -image_a_path={path to image A} -image_b_path={path to image B}", I can open butterfly viewer, **with the two images loaded already and also the sliding overlay created.**
I imagine up to four such arguments may be provided, as butterfly viewer can compare up to 4 images.

With this feature, combined with various automation/efficiency tools out there, one can create shortcuts to quickly start the comparison.

**Comment by larsmaxfield** [comment]
That would indeed be a useful feature. Thanks for the request.

I think the eventual implementation will be straightforward, but I don't have experience creating command line interfaces for Python or executables. So this may take a little while. Will keep you updated.

**Comment by larsmaxfield** [comment]
For my own notes (and anyone else interested), the broad solution will need to involve:

1. Python input arguments on main call in butterfly_viewer.py
2. PyInstaller's generated EXE accepting command line arguments
3. Inno Setup generated setup installer carrying over those command line arguments

PyInstaller
- https://stackoverflow.com/questions/25984395/how-to-input-arguments-after-compiling-python-program-with-pyinstaller

Inno Setup
- Use Parameters to add command line arguments to EXE: https://stackoverflow.com/questions/40029270/how-to-run-application-in-cmd-exe-with-inno-setup

**Comment by 0xKZ** [comment]
I came here to make this same request - invoking this tool as part of an approval workflow is something I would be interested in, and to do that in an automated fashion I would prefer command line parameters.

Regarding the implementation: 

@larsmaxfield consider using 'argparse': https://docs.python.org/3/library/argparse.html

I have used this in the past and it is much simpler than manually looking at argc/argv. After that is implemented, you _shouldn't_ need to do anything special to get the built exe to use them. Would you be open to a pull request if I find the time?

**Comment by larsmaxfield** [comment]
@0xKZ thanks for the tip and offer — indeed I'm always open for a PR.

Bear in mind I was learning Python and PyQt in the process of building this app, so the code consistency and quality might not be so stellar. If you see the need to change the internals to make it easier (or simply possible) to implement this feature, feel free to do so.

**Comment by 0xKZ** [comment]
> @0xKZ thanks for the tip and offer — indeed I'm always open for a PR.
> 
> Bear in mind I was learning Python and PyQt in the process of building this app, so the code consistency and quality might not be so stellar. If you see the need to change the internals to make it easier (or simply possible) to implement this feature, feel free to do so.

I took a crack at it and it was actually pretty easy and minimal to do this. See: https://github.com/olive-groves/butterfly_viewer/pull/74

No worries about the architecture - I haven't used Qt since 2012 so I am less familiar than you there ;)

Thankfully this didn't require any structural changes and it opens the door to more automation being integrated with the tool in the future via other command line arguments.

**Comment by larsmaxfield** [comment]
Thanks for the PR @0xKZ. Changes are now in `main` with these combinable arguments:

`--hide` hide the interface
```
python butterfly_viewer.py --hide
```

`--fullscreen` go fullscreen
```
python butterfly_viewer.py --fullscreen
```

`--paths` create individual (side by side) image windows with one or more paths
```
python butterfly_viewer.py --paths image1.jpg image2.jpg
```

`--overlay_path_...` create sliding overlay window
```
python butterfly_viewer.py --overlay_path_main_topleft image1.jpg --overlay_path_topright image2.jpg --overlay_path_bottomleft image3.jpg
```

Still need to verify this works with the installed executable #76 and then implement in a new release #75.
