### ISSUE TITLE
[Feature] <title>Display Image File Name

### ISSUE THREAD

**Issue by GOD-TheSupreme** [olive-groves/butterfly_viewer#70]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When comparing several visually identical (almost) images its difficult to relate the previews to the original files as file names are not shown in the previews.
![Viewer screenshot 2024-08-18 170349](https://github.com/user-attachments/assets/d8a55c45-48c1-4385-9600-c3538c92523a)
![Image Files Names](https://github.com/user-attachments/assets/bfe86805-c1c7-454d-904a-567b3eb06053)

### Describe the solution you'd like

Some thing like this:
![Compared in Faststone Image Viewer](https://github.com/user-attachments/assets/a292892b-d550-40aa-b44b-202b456bb675)

### Describe alternatives you've considered

Using Fsatstone Image Viewer to compare images which previews four image files only at once.

### Anything else?

Nothing that comes to mind right now.

**Comment by larsmaxfield** [comment]
Thanks @GOD-TheSupreme. Indeed a useful feature.

Another user made a similar request in #68, so I'm going to close this one as I consider it a duplicate.
